### PR TITLE
Update channels.yml

### PR DESCRIPTION
**Pull request by ankitprahladsoni**

### CODE REVIEW

**Comment by sizovs** [comment]
Hey! Thanks for contributing this. Unfortunately, the bot does not accept such content. See https://github.com/watch-devtube/contrib/issues/320. 

Could you please contribute missing channels? 🙌

**Comment by ankitprahladsoni** [comment]
The PR was to add videos only from the playlist and not add all channels from the playlist.
let me know if I missed anything.

**Comment by sizovs** [comment]
@ankitprahladsoni this won't work – the crawler will add videos from Alex Sinclair channel (he has 0). Crawler does not support playlists that with foreign videos.

**Comment by ankitprahladsoni** [comment]
oh, get it
I will add them individually
More karma for me 😄

**Comment by sizovs** [comment]
Indeed! 🚀

**Pull request closed without merging**
