### PR TITLE
Add Afup - Association française des utilisateurs de PHP

### PR DESCRIPTION
**Pull request by mehdichaouch**
https://www.youtube.com/user/afupPHP

### CODE REVIEW

**Comment by mehdichaouch** [comment]
Hey AFUP I add your channel :popcorn: @xgorse @jmfontaine @xavierlacot @mikaelrandy @mikaelkael @BenoitLeveque @agallou @jewome62 @webaaz @krichprollsch @odolbeau @macintoshplus @jacquesbh @Korbeil @Halleck45 @omansour @xavierleune @oallain @maxhelias + @fzaninotto :wink:

**Comment by mehdichaouch** [comment]
👀

**Review by maxhelias — APPROVED** [review]

**Comment by xavierleune** [comment]
Hi,
Thanks for the highlight, I'll pass this proposal to the afup team, they'll decide if they want to proceed further.

**Comment by mehdichaouch** [comment]
Hello @xavierleune,

I don't understand:
> they'll decide if they want to proceed further

No need for afup team to do something.
I tagged afup team just to let them know that your great conferences will be listed in dev.tube.

**Comment by sizovs** [comment]
Hey @mehdichaouch  

Thanks for your contribution. We've refactored DevTube so it's a curated list of the best videos. If you believe some of the listed videos are worth adding – please contribute via UI. 

Thanks!

**Pull request closed without merging**
