### PR TITLE
Update -C2js48fAQU.yml

### PR DESCRIPTION
**Pull request by yoannfleurydev**

### CODE REVIEW

**Comment by sizovs** [comment]
Hey @yoannfleurydev 

Thanks for your contribution. Speaker's Twitter handle is missing for this one

**Comment by yoannfleurydev** [comment]
This speaker doesn't have a Twitter account, is this mandatory to be merged? I can remove the speaker part if needed. 🙂

**Comment by sizovs** [comment]
@yoannfleurydev Yeah, the speaker's Twitter handle is mandatory

**Comment by yoannfleurydev** [comment]
👌🏻 I removed the speaker part then. 😉

**Pull request merged**
