### PR TITLE
Update channels.yml

### PR DESCRIPTION
**Pull request by biezhi**

### CODE REVIEW

**Comment by aadamovich** [comment]
@biezhi what would be your channel name in English?

**Comment by biezhi** [comment]
@aadamovich Hi, I modified the English channel name to: `Biezhi Dev Channel`

**Comment by aadamovich** [comment]
Thanks, @biezhi! I will keep this pull request open for a while. We would really like to accept technical videos from all over the world, but we first need to implement a better multi-language support in our index and web front-end. But don't worry, pull request will be merged eventually.

**Comment by aadamovich** [comment]
Adding for the reference:

https://github.com/watch-devtube/web/issues/44
https://github.com/watch-devtube/web/issues/55

**Comment by biezhi** [comment]
@aadamovich Thank you for your contribution. 😜

**Pull request merged**
