### PR TITLE
Add 4 channels

### PR DESCRIPTION
**Pull request by gokaygurcan**
Hi, 
I added these four channels: 

- Fun Fun Function
- ZEIT
- DevTips
- GOTO

They all are very active and have lost of subscribers. I believe it'll be a good addition.

I hope you'll consider accepting them. Thanks in advance!

Cheers,
G.

### CODE REVIEW

**Comment by aadamovich** [comment]
Thanks for your pull request! We will merge this pull request later. At the moment we are at our indexing capacity (write operations to Algolia) and we need to wait 2 weeks for rate limits to be reset.

**Comment by gokaygurcan** [comment]
Hey @aadamovich, 
no worries, whenever it suits you. 

thanks for letting me know though!

cheers,
G.

**Comment by aadamovich** [comment]
I added Zeit, we already had GOTO, and I removed Fun Fun and DevTips, because those videos are not in conference format

**Comment by gokaygurcan** [comment]
ah, it's my bad, i didn't see it. thanks a lot!

**Pull request merged**
