### PR TITLE
Add JeffConf and ServerlessDays playlists

### PR DESCRIPTION
**Pull request by alexcasalboni**
Here are the playlists I mentioned in #395  :)

### CODE REVIEW

**Comment by sizovs** [comment]
Hi @alexcasalboni 

Thanks for your contribution! Do you think it's a good idea to ingest all videos from JezzConf and ServerlessDays channels, instead of specific playlists? That would make new channel videos appear automatically on dev.tube.

We usually go with playlists only if a channel contains some irrelevant content. What do you think?

**Comment by alexcasalboni** [comment]
Thanks for the quick feedback, @sizovs :)

There is no irrelevant content on the YouTube channel, although each playlist is related to an independent event, city, and organizing team. And there are individual playlists for each year too, so I thought it'd make sense to group them properly.

Unless the dev.tube magic already does that automatically ^_^

**Comment by sizovs** [comment]
@alexcasalboni dev.tube will do all the heavy work. Would you mind contributing 2 channels instead? 👌

**Comment by alexcasalboni** [comment]
Sure, sounds great! I should have asked first :)

But why two channels then?

Everything is on this YT channel: https://www.youtube.com/channel/UCYzAnR_SebAmLRkKIbK_YoQ

**Comment by sizovs** [comment]
@alexcasalboni merged ❤️

**Pull request closed without merging**
